# See https://bevyengine.org/learn/quick-start/getting-started/setup/#generic-sharing.
[target.x86_64-unknown-linux-gnu]
rustflags = [
  # (Nightly) Make the current crate share its generic instantiations
  "-Zshare-generics=y",
]